MUMScrum.Web/Controllers/UserStoryController.cs
using System.Web.Mvc;
using MUMScrum.Model;
using MUMScrum.BusinessService;
using MUMScrum.HR;
using System.Collections.Generic;
using MUMScrum.Web.Helpers;
using System.Net;
using MUMScrum.Web.Authorization;

namespace MUMScrum.Web.Controllers
{
    [ScrumAuthorization]
    public class UserStoryController : Controller
    {
        private IUserStoryService service = new UserStoryService();
        private IHRManager HrService = new HRManager();
        private ISprintService SprintService = new SprintService();
        private IReleaseBacklogService ReleaseSevice = new ReleaseBacklogService();
        private IProductBacklogService ProductService = new ProductBacklogService();

        // GET: UserStory
        public ActionResult Index()
        {
            return View(service.GetAll());
        }

        public ActionResult GetUserStoriesByUId(int UserId)
        {
            if (Utility.UserInRole(RoleEnum.Developer, Session))
                return View("Index", service.GetAllByDeveloperId(UserId));
            else
                return View("Index", service.GetAllByTesterId(UserId));
        }

        // GET: UserStory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserStory userStory = service.GetUserStoryById(id.Value);
            if (userStory == null)
            {
                return HttpNotFound();
            }
            return View(userStory);
        }

        //// GET: UserStory/Create
        [ScrumAuthorization(Roles = "ProductOwner")]
        public ActionResult Create(int? ProductId, int? ReleaseId, int? SprintId)
        {
            ViewBag.DevelopedId = new SelectList(HrService.GetAllDevelopers(), "Id", "FirstName");
            ViewBag.ProductBackLogId = new SelectList(ProductService.GetAllProductBackLogsByOwner(Utility.GetEmployeeSession(this.Session).Id), "Id", "Name", ProductId);
            ViewBag.ReleaseId = new SelectList(new List<ReleaseBacklog>());
            ViewBag.SprintId = new SelectList(new List<Sprint>(), "Id", "SprintName");
            ViewBag.TesterId = new SelectList(HrService.GetAllTesters(), "Id", "FirstName");
            return View(new UserStory
            {
                SprintId = SprintId,
                ReleaseId = ReleaseId
            });
        }

        // POST: UserStory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ScrumAuthorization(Roles = "ProductOwner")]
        public ActionResult Create([Bind(Include = "Id,Title,Description,DevelopedId,TesterId,ProductBackLogId,ReleaseId,SprintId,DevEstimate , TestEstiamte , DevActual ,TestActual ")] UserStory userStory)
        {
            if (ModelState.IsValid)
            {
                service.CreateUserStory(userStory);
                if (!string.IsNullOrEmpty(Request["sprintId"]))
                {
                    return RedirectToAction("Details", "Sprint", new { id = userStory.SprintId });
                }
                else if (!string.IsNullOrEmpty(Request["releaseId"]))
                {
                    return RedirectToAction("Details", "ReleaseBacklog", new { id = userStory.ReleaseId });
                }
                else if (!string.IsNullOrEmpty(Request["productId"]))
                {
                    return RedirectToAction("Details", "ProductBacklogs", new { id = userStory.ProductBackLogId });
                }

            }

            ViewBag.DevelopedId = new SelectList(HrService.GetAllDevelopers(), "Id", "FirstName");
            ViewBag.ProductBackLogId = new SelectList(ProductService.GetAllProductBackLogsByOwner(Utility.GetEmployeeSession(this.Session).Id), "Id", "Name");
            ViewBag.ReleaseId = new SelectList(ReleaseSevice.GetAll(), "Id", "ReleaseName");
            ViewBag.SprintId = new SelectList(SprintService.GetAll(), "Id", "SprintName");
            ViewBag.TesterId = new SelectList(HrService.GetAllTesters(), "Id", "FirstName");
            return View(userStory);
        }

        // GET: UserStory/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserStory userStory = service.GetUserStoryById(id.Value);
            if (userStory == null)
            {
                return HttpNotFound();
            }
            Employee User = Utility.GetEmployeeSession(this.Session);
            ViewBag.ProductBackLogId = new SelectList(ProductService.GetAllProductBackLogsByOwner(User.Id), "Id", "Name", userStory.ProductBackLogId);
            ViewBag.ReleaseId = new SelectList(new List<ReleaseBacklog>());
            ViewBag.SprintId = userStory.ReleaseId == null ? new SelectList(new List<Sprint>()) : new SelectList(SprintService.GetAllSprintsByRelId(userStory.ReleaseId.Value), "Id", "SprintName");

            if (Utility.UserInRole(RoleEnum.ProductOwner, Session))
                return View("_POEdit", userStory);

            ViewBag.DevelopedId = new SelectList(HrService.GetAllDevelopers(), "Id", "FirstName", userStory.DevelopedId);
            ViewBag.TesterId = new SelectList(HrService.GetAllTesters(), "Id", "FirstName", userStory.TesterId);

            if (Utility.UserInRole(RoleEnum.ScrumMaster, Session))
                return View("_SMEdit", userStory);

            else if (Utility.UserInRole(RoleEnum.Developer, Session) || Utility.UserInRole(RoleEnum.Tester, Session))
                return View("_EmpEdit", userStory);

            return View(userStory);
        }

        // POST: UserStory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,DevelopedId,TesterId,ProductBackLogId,ReleaseId,SprintId,DevEstimate , TestEstiamte , DevActual ,TestActual ")] UserStory userStory)
        {
            Employee User = Utility.GetEmployeeSession(this.Session);
            if (ModelState.IsValid)
            {
                service.UpdateUserStory(userStory, User.RoleId);
                return RedirectUrl(service.GetUserStoryById(userStory.Id));
            }
            ViewBag.ProductBackLogId = new SelectList(ProductService.GetAllProductBackLogsByOwner(User.Id), "Id", "Name", userStory.ProductBackLogId);
            ViewBag.ReleaseId = new SelectList(new List<ReleaseBacklog>());
            ViewBag.SprintId = new SelectList(SprintService.GetAllSprintsByRelId(userStory.ReleaseId.Value), "Id", "SprintName");

            if (Utility.UserInRole(RoleEnum.ProductOwner, Session))
                return View("_POEdit", userStory);

            ViewBag.DevelopedId = new SelectList(HrService.GetAllDevelopers(), "Id", "FirstName", userStory.DevelopedId);
            ViewBag.TesterId = new SelectList(HrService.GetAllTesters(), "Id", "FirstName", userStory.TesterId);

            if (Utility.UserInRole(RoleEnum.ScrumMaster, Session))
                return View("_SMEdit", userStory);

            else if (Utility.UserInRole(RoleEnum.Developer, Session) || Utility.UserInRole(RoleEnum.Tester, Session))
                return View("_EmpEdit", userStory);
            return View(userStory);
        }

        private RedirectToRouteResult RedirectUrl(UserStory userStory)
        {
            var emp = Utility.GetEmployeeSession(Session);
            if ((RoleEnum)emp.RoleId == RoleEnum.Developer || (RoleEnum)emp.RoleId == RoleEnum.Tester)
                return RedirectToAction("GetUserStoriesByUId", new { UserId = emp.Id });

            if (Request["return"] == null) return RedirectToAction("Index", "Home");
            switch (Request["return"].ToLower())
            {

                case "sprint":
                    return RedirectToAction("Details", "Sprint", new { id = userStory.SprintId });
                case "product":
                    return RedirectToAction("Details", "ProductBacklogs", new { id = userStory.ProductBackLogId });
                case "release":
                default:
                    return RedirectToAction("Details", "ReleaseBacklog", new { id = userStory.ReleaseId  });
            }
        }

        //// GET: UserStory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserStory userStory = service.GetUserStoryById(id.Value);
            if (userStory == null)
            {
                return HttpNotFound();
            }
            return View(userStory);
        }

        // POST: UserStory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisUs = service.GetUserStoryById(id);

            var userStory = new UserStory
            {
                SprintId = thisUs.SprintId,
                ProductBackLogId = thisUs.ProductBackLogId,
                ReleaseId = thisUs.ReleaseId,
            };

            try
            {
                if (service.DeleteUserStory(id))
                {
                    service.DeleteRelatedLogs(id);
                }
            }
            catch (System.Exception ex)
            {
                TempData.Add("Message", ex.Message);
            }
            
            return RedirectUrl(userStory);
        }

        protected override void Dispose(bool disposing)
        {

MUMScrum.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- start: Meta -->
    <meta charset="utf-8">
    <title>MUMScrum App - By SPRK</title>
    @*<meta name="description" content="Bootstrap Metro Dashboard">
        <meta name="author" content="Dennis Ji">
        <meta name="keyword" content="Metro, Metro UI, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">*@
    <!-- end: Meta -->
    <!-- start: Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- end: Mobile Specific -->
    <!-- start: CSS -->
    <link id="bootstrap-style" href="~/UI_Design2/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/UI_Design2/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link id="base-style" href="~/UI_Design2/css/style.css" rel="stylesheet">
    <link id="base-style-responsive" href="~/UI_Design2/css/style-responsive.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>
    <!-- end: CSS -->
    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <link id="ie-style" href="css/ie.css" rel="stylesheet">
    <![endif]-->
    <!--[if IE 9]>
        <link id="ie9style" href="css/ie9.css" rel="stylesheet">
    <![endif]-->
    <!-- start: Favicon -->
    <link rel="shortcut icon" href="~/UI_Design2/img/favicon.ico">
    <!-- end: Favicon -->

    <style>
        .text-danger {
            color: #b94a48;
        }
    </style>


</head>
<body>
    <!-- start: Header -->
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="~/"><img src="~/UI_Design/img/Logo.gif" style="height: 35px;width: 191px;" alt="" /></a>

                <!-- start: Header Menu -->
                <div class="nav-no-collapse header-nav">
                    <ul class="nav pull-right">
                        <!-- start: User Dropdown -->
                        <li class="dropdown">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="halflings-icon white user"></i> @MUMScrum.Web.Helpers.Utility.GetLoggedInEmployeeName(this.Session)
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-menu-title">
                                    <span>Account Settings</span>
                                </li>
                                <li><a href="/Employees/UpdateProfile/@MUMScrum.Web.Helpers.Utility.GetEmployeeSession(this.Session).Id"><i class="halflings-icon user"></i> Profile</a></li>
                                <li>
                                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <a href="javascript:document.getElementById('logoutForm').submit()"><i class="halflings-icon off"></i> Logout </a>
                                    }
                            </ul>
                        </li>
                        <!-- end: User Dropdown -->
                    </ul>
                </div>
                <!-- end: Header Menu -->

            </div>
        </div>
    </div>
    <!-- start: Header -->

    <div class="container-fluid-full">
        <div class="row-fluid">

            <!-- start: Main Menu -->
            <div id="sidebar-left" class="span2">
                <div class="nav-collapse sidebar-nav">
                    <ul class="nav nav-tabs nav-stacked main-menu">
                        <li><a href="~/"><i class="icon-bar-chart"></i><span class="hidden-tablet"> Dashboard</span></a></li>
                        @*<li><a href="messages.html"><i class="icon-envelope"></i><span class="hidden-tablet"> Messages</span></a></li>
                            <li><a href="tasks.html"><i class="icon-tasks"></i><span class="hidden-tablet"> Tasks</span></a></li>*@
                        @if (MUMScrum.Web.Helpers.Utility.UserInRole(MUMScrum.Model.RoleEnum.ProductOwner, Session))
                        {
                            <li id="ProductsMenu"> <a  href="~/ProductBacklogs"><i class="icon-eye-open"></i><span class="hidden-tablet"> Products</span></a></li>
                        }
                        @if (MUMScrum.Web.Helpers.Utility.UserInRole(MUMScrum.Model.RoleEnum.ScrumMaster, Session))
                        {
                            <li id="ReleasesMenu"><a href="~/ReleaseBacklog?ScrumId=@MUMScrum.Web.Helpers.Utility.GetEmployeeSession(Session).Id">
                                <i class="icon-eye-open"></i><span class="hidden-tablet"> Releases</span></a></li>
                        }


                        @if (MUMScrum.Web.Helpers.Utility.UserInRole(MUMScrum.Model.RoleEnum.Developer, Session))
                        {
                            <li id="UstoriesMenu">
                               @*@Html.ActionLink("User Stories", "GetUserStoriesByUId","UserStory", new { UserId = @MUMScrum.Web.Helpers.Utility.GetEmployeeSession(Session).Id }, null)*@
                                <a href="~/UserStory/GetUserStoriesByUId?UserId=@MUMScrum.Web.Helpers.Utility.GetEmployeeSession(Session).Id">
                                    <i class="icon-eye-open"></i><span class="hidden-tablet"> User Stories</span>
                                </a>
                            </li>
                        }

                        @if (MUMScrum.Web.Helpers.Utility.UserInRole(MUMScrum.Model.RoleEnum.Tester, Session))
                        {
                            <li id="UstoriesMenu">
                                <a href="~/UserStory/GetUserStoriesByUId?UserId=@MUMScrum.Web.Helpers.Utility.GetEmployeeSession(Session).Id">
                                    <i class="icon-eye-open"></i><span class="hidden-tablet"> User Stories </span>
                                </a>
                            </li>
                        }

                        @if (MUMScrum.Web.Helpers.Utility.UserInRole(MUMScrum.Model.RoleEnum.HR, Session))
                        {
                            <li id="EmployeesMenu"><a href="~/Employees"><i class="icon-dashboard"></i><span class="hidden-tablet"> Employees</span></a></li>
                        }

                    </ul>
                </div>
            </div>
            <!-- end: Main Menu -->

            <noscript>
                <div class="alert alert-block span10">
                    <h4 class="alert-heading">Warning!</h4>
                    <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
                </div>
            </noscript>

            <!-- start: Content -->
            <div id="content" class="span10">
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="~/">Home</a>
                        <i id="rightangle" class="icon-angle-right"></i>
                        <a href="~/" id="BreadCrumMenu"></a>
                    </li>
                </ul>
                @RenderBody()
            </div><!--/.fluid-container-->
            <!-- end: Content -->
        </div><!--/#content.span10-->
    </div><!--/fluid-row-->

    <div class="modal hide fade" id="myModal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Settings</h3>
        </div>
        <div class="modal-body">
            <p>Here settings can be configured...</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <a href="#" class="btn btn-primary">Save changes</a>
        </div>
    </div>

    <div class="clearfix"></div>

    <footer>
        <p>
            <span style="text-align:left;float:left">&copy; 2015 <a href="http://jiji262.github.io/Bootstrap_Metro_Dashboard/" alt="Bootstrap_Metro_Dashboard">SPRK Group</a></span>

        </p>
    </footer>
   
    <!-- start: JavaScript-->
    <script src="~/UI_Design2/js/jquery-1.9.1.min.js"></script>
    <script src="~/UI_Design2/js/jquery-migrate-1.0.0.min.js"></script>

    <script src="~/UI_Design2/js/jquery-ui-1.10.0.custom.min.js"></script>

    <script src="~/UI_Design2/js/jquery.ui.touch-punch.js"></script>

    <script src="~/UI_Design2/js/modernizr.js"></script>

    <script src="~/UI_Design2/js/bootstrap.min.js"></script>

    <script src="~/UI_Design2/js/jquery.cookie.js"></script>

    <script src='~/UI_Design2/js/fullcalendar.min.js'></script>

    <script src='~/UI_Design2/js/jquery.dataTables.min.js'></script>
    <script src="~/UI_Design2/js/excanvas.js"></script>
    <script src="~/UI_Design2/js/jquery.flot.js"></script>
    <script src="~/UI_Design2/js/jquery.flot.pie.js"></script>
    <script src="~/UI_Design2/js/jquery.flot.stack.js"></script>
    <script src="~/UI_Design2/js/jquery.flot.resize.min.js"></script>

    <script src="~/UI_Design2/js/jquery.chosen.min.js"></script>

    <script src="~/UI_Design2/js/jquery.uniform.min.js"></script>

    <script src="~/UI_Design2/js/jquery.cleditor.min.js"></script>

    <script src="~/UI_Design2/js/jquery.noty.js"></script>

    <script src="~/UI_Design2/js/jquery.elfinder.min.js"></script>

    <script src="~/UI_Design2/js/jquery.raty.min.js"></script>

    <script src="~/UI_Design2/js/jquery.iphone.toggle.js"></script>

    <script src="~/UI_Design2/js/jquery.uploadify-3.1.min.js"></script>

    <script src="~/UI_Design2/js/jquery.gritter.min.js"></script>

    <script src="~/UI_Design2/js/jquery.imagesloaded.js"></script>

    <script src="~/UI_Design2/js/jquery.masonry.min.js"></script>

    <script src="~/UI_Design2/js/jquery.knob.modified.js"></script>

    <script src="~/UI_Design2/js/jquery.sparkline.min.js"></script>

    <script src="~/UI_Design2/js/counter.js"></script>

    <script src="~/UI_Design2/js/retina.js"></script>
    <script src="~/UI_Design2/js/custom.js"></script>
    <!-- end: JavaScript-->
    @RenderSection("scripts", required: false)

</body>
</html>